import {Text} from "react-native";
import React from "react";

export default {
  language_english: "EN",
  language_bangla: "বাংলা",
  login: "Login",
  save: "Save",
  submit: "Submit",
  accept: "Accept",
  decline: "Decline",
  continue_txt: "Continue",
  next: "Next",
  user_ID: "Enter Your User ID",
  new_signup: "New in CityTouch?",
  sign_up_now: "Sign up now!",
  fgt_uid_pwd_pin: "Forgot User ID or Password or PIN ?",
  right_reserved: "All rights reserved. Copyright @2021 The City Bank Limited V 1.0",
  faqs: "FAQs",
  atm_branch: "ATM & Branch",
  info: "Info",
  privacy: "Privacy",
  contact: "Contact",
  select_contact_type: "Select Contact Type",
  select_actNo: "Select Account Number",
  credentialDetails: "Credential Details",
  selectionType: "Selection Type *",
  selectType: "Select Type",
  selectActType: "Select Account Type",
  type_act: "Type of Account *",
  actNo: "Account Number",
  actName: "Account Name",
  actNo_here: "Enter account number here",
  selectCard: "Select Card",
  transactionPin: "Transaction PIN",
  loginPin: "Login PIN",
  setLoginPIn: "Set Login PIN",
  enterCardPin: "Card PIN",
  enterExpiry: "Expiry Date",
  enterCardExpiry: "Select Card Expiry Date",
  enterPinHere: "Enter PIN here",
  otpType: "OTP Type:",
  back_txt: "Back",
  mark_field_mandatory: "Marked fields are mandatory",
  noRecord: "No Records Found",
  ok: "OK",
  passwordTxt: "Enter Your Password",
  expiryDate: "Enter Expiry Date here",
  credit_card_no: "Card Number",
  cardName: "Card Name",
  enter_card_no: "Enter Card Number here",
  otp: "OTP",
  otp_txt: "One Time Password",
  otp_sent: "Sent OTP",
  otp_description: "Please enter the OTP sent to your registered mobile/email ",
  otp_fgt_pwd: "to process forgot password",
  otp_fgt_pin: "to process forgot PIN",
  otp_fgt_uid: "to process forgot User ID",
  otp_activate: "to activate Citytouch Digital Banking Service",
  otp_signup: "to process registration in Citytouch Digital Banking Service",
  otp_pwd: "to change password in Citytouch Digital Banking Service",

  otp_input_placeholder: "Enter 4 Digit One Time Password(OTP)",
  dnReceiveOTP: "Did not receive your OTP? ",
  sendAgain: "Send Again",
  termsCondition: "Terms and Conditions",
  emailAddress: "Email Address",
  mobileNo: "Mobile Number",
  sms: "SMS",
  email: "EMAIL",
  otpViaMob: "You will receive an One Time Password (OTP) via SMS to Mobile Number: ",
  otpViaEmail: "You will receive an One Time Password (OTP) via Email to Email Address: ",
  register_title: "Citytouch Online Registration",
  signupWithAccount: "SIGN UP WITH ACCOUNT",
  signupWithCard: "SIGN UP WITH CREDIT/PREPAID CARD",
  welcome_signup: "Welcome to CityTouch Online Registration process. Please enter your ",
  accountNo: "account Number",
  cardNoInput: "card Number",
  debitCard: "debit card details",
  provideDetails: "Welcome to CityTouch Online Registration process. Please provide below details.",
  account: "Accounts",
  city_pay: "CityPay",
  more: "More",
  payments: "Payments",
  transfer: "Transfer",
  goodEvening: "Good Evening, MD. GOLAM MOSTAFA",
  avail_balance: "Available Balance",
  view_balance: "View Balance",
  fatherName: "Father Name",
  motherName: "Mother Name",
  et_father_name: "Enter Father Name",
  et_mother_name: "Enter Mother Name",
  et_dob: "Date Of Birth",
  select_dob: "Enter Date of Birth",
  yes_txt: "Yes",
  no_txt: "No",
  user_id: "User ID",
  user_id_enter: "Enter User ID here",
  conf_mobile: "Confirm Mobile Number",
  conf_email: "Confirm Email Address",
  setPwdTxt: "Set Password",
  etPasswordTxt: "Enter Password here",
  enterTransactionPin: "Enter transaction PIN",
  last_trans_date: "Last Transaction Date",
  last_trans_amount: "Last Transaction Amount",
  personalise_profile: "Personalise Profile",
  change_contact: "Change Contact Details",
  change_login_password: "Change Login Password",
  change_login_pin: "Change Login PIN",
  change_transaction_pin: "Change Transaction PIN",
  upload_documents: "Upload Supporting Document",
  upload_docs: "Upload Document",
  withdrawChk: "Withdrawn",
  dateTitle: "Date",
  typeTitle: "Type",
  current_balance: "Current Balance",
  amountTitle: "Amount",
  recent_trans: "Recent Transactions",
  descriptionTitle: "Description",
  depositChk: "Deposit",
  conf_loginPin: "Confirm Login PIN",
  customerName: "Customer Name",
  changeFor: "Change",
  login_configure_profile: "Login Configure Profile",
  config_information: "Please configure below information.",
  alias: "Alias",
  et_alias: "Enter Alias here",
  set_transaction_pin: "Set Transaction Pin",
  Transaction_Pin: "Transaction Pin",
  Confirm_Pin: "Confirm Transaction Pin",
  new_pin_txt: "New PIN",
  et_new_pin_txt: "Enter New Pin",
  confirm_pin_txt: "Confirm New Pin",
  et_confirm_pin_txt: "Enter Confirm New Pin",
  open_account: "Open Account",
  type_contact: "Contact Type *",

  Language_M: [
    {label: "English", value: 0},
    {label: "বাংলা", value: 1},
  ],
  Language_P: "Language Preference",
  Login_W: "Login With",
  Login_M: [
    {label: "Password", value: 0},
    {label: "Pin", value: 1},
    {label: "Biometric", value: 2},
  ],

  contactList: [
    {label: "Change Mobile Number", value: 0},
    {label: "Change Email Address", value: 1},
  ],

  DocumentRequiredForArr: [
    {label: "Change Mobile Number", value: 0},
    {label: "Change Email Address", value: 1},
  ],


  supportDocument: "Supporting Document",
  selectDocument: "Select the supporting document",
  documentNo: "Document Number",
  documentTypeArr: [
    {label: "NID", value: 1},
    {label: "Rental Deed", value: 2},
    {label: "Utility Bill Copy", value: 3},
    {label: "Property Purchase Document", value: 4},
    {label: "Business Card", value: 5},
    {label: "Passport", value: 6},
    {label: "Driving Licence", value: 7},
  ],


  /*success messages*/
  success_fgt_uid: "User id has been sent via SMS/Email",
  success_msg: "Successfully done",
  success_saved: "Successfully Saved",
  success_register: "Successfully Registered",


  /*error message*/
  require_user_id: "User ID is Required",
  require_length_user_id: "Length should be minimum 8",
  require_pwd: "Password is Required",
  cityTouchUserId: "CityTouch User ID",
  requireUserId: "CityTouch User ID is Required",
  enterUserId: "Enter User ID here",
  deviceChangeTxt: "You will be logged out from all other devices. From now on this will be your primary device. Do you want to continue.",
  invalidCredential: "Invalid UserId or Password",
  require_mobile: "Mobile Number is Required",
  require_email: "Email Address is Required",
  email_not_valid: "Email Address is not Valid",
  maxOneMB: "Maximum 1 MB size of file allowed",
  max200KB: "Maximum 200 KB size of image allowed",


  /*confirmation message*/
  logout_confirm: "Are you sure want to Logout?",


  /*arrays*/
  optionTypeArr: [
    {key: "0", label: "Forgot User ID", value: 0},
    {key: "1", label: "Forgot Password", value: 1},
    {key: "2", label: "Forgot PIN", value: 2},
  ],

  accountTypeArr: [
    {key: "0", label: "Account Number", value: 0},
    {key: "1", label: "Credit Card Number", value: 1}
  ],

  otp_props: [
    {label: "SMS", value: 0},
    {label: "Email", value: 1},
    {label: "Both", value: 2},
  ],

  userIdOption: [
    {label: "User ID", value: 0},
    {label: "Preferred User ID", value: 1}
  ],

  conf_user_ID: "Confirm User ID",
  login_pin: "Login Pin",

  pwd_txt: "New Password",
  new_pass_txt: "Enter new password",
  new_trans_pin_txt: "Enter new transaction pin",
  conf_new_trans_pin_txt: "Confirm new transaction pin",
  conf_new_pass_txt: "Confirm new password",
  signup: "Sign up",
  fgt_pwd_uid: "Forgot User ID or Password?",
  fgt_uid: "Forgot User ID?",
  fgt_pwd: "Forgot Password?",
  fgt_pin: "Forgot PIN?",

  conf_trans_pin: "Confirm Transaction PIN",

  et_pin: "Enter PIN",
  et_card_pin: "Enter card PIN",

  acc_no: "Enter Account Number",
  card_no: "Enter Card Number",
  acc_name: "Account Name",
  donot_have_act: "Don't have bank account yet?",

  creditcard_name: "Enter Credit Card Name",
  prepaidcard_name: "Enter Prepaid Card Name",
  mobile: "Mobile Number",


  preferred_user_id: "Preferred User ID",
  read_term: "I have read and agree to the ",
  term_condition: "terms and conditions",
  term_condition_title: "Terms and Conditions",
  otp_type: "OTP Type",
  login_type: "Select Login Preference",
  language_type: "Select Language Preference",
  sms_txt: "SMS",
  email_txt: "Email",
  both_txt: "both",
  provide_card: "Please provide your debit card information",
  mmyy_txt: "Card expiry MM / YY",
  mmyy: "MM / YY",
  enter_pin: "Enter Card PIN",


  et_set_user_id: "Set User ID",
  er_set_pwd: "Set Password",
  er_otpPin: "Enter received OTP",
  et_transPin: "Enter transaction PIN",
  pwd: "Password",
  submit_txt: "Submit",
  otp_sent_txt: "Get OTP",

  new_pwd_txt: "New Password",

  confirm_pwd_txt: "Confirm Password",
  select_request: "Select Request",
  prepaid_card: "Using Prepaid Card",
  credit_card: "Using Credit Card",
  using_act_no: "Using Account Number",

  with_prepaid_card: "Sign up with Prepaid Card",
  with_credit_card: "Sign up with Credit Card",
  with_act_no: "Sign up with Account Number",

  provide_info: "Please provide below information",
  provide_debit_card: "Please provide your debit card information",
  provide_credit_card: "Please provide your credit card information",
  provide_prepaid_card: "Please provide your prepaid  card information",

  deposit_account: "Deposit Accounts",
  summary_account: "Account Summary",
  fd: "Fixed Deposit",
  fundsTransfer: "Fund Transfer",
  cheque: "Cheque Details",
  cards: "Card\nDetails",
  other_services: "Other Services",

  loan: "loan",
  loan_accounts: "Loan Accounts",
  loan_scheduler: "Loan Scheduler",
  loan_against_deposit: "Loan Against Deposit",
  loan_interest_certificate: "Loan Interest Certificate",

  personalize_profile: "Personalise Profile",
  change_pwd: "Change Password",
  change_transaction_pin: "Change Transaction PIN",
  slogan: "Dear customer, Welcome to CityTouch Mobile Banking. For help Call: ",
  new_login_pin: "New Login PIN",
  conf_new_login_pin: "Confirm New Login PIN",

  fd_accounts: "FD accounts",
  new_fd_accounts: "New FD",


  cheque_book_details: "Cheque Book Details",
  cheque_status: "Cheque Status",
  cheque_book_request: "Cheque Book ApiRequest",
  cheque_book_request_detail: "Cheque Book ApiRequest Details",
  cheque_request_stop: "Cheque Stop ApiRequest",
  cheque_intimation: "Cheque intimation(Positive Pay)",
  view_cheque_intimation: "View Cheque intimation(Positive Pay)",


  current_saving: "Current Saving Accounts",
  term_deposit: "Term Deposits",
  credit_account: "Credit Card Accounts",

  present_address: "Enter your present address",
  communication_address: "Enter your Communication address",
  numberVal: "Enter document number",
  select_file: "Choose File",
  update: "Update",
  cancel: "Cancel",

  current_mobile_no: "Current Mobile Number",
  new_mobile_no: "New Mobile Number",
  conf_new_mobile_no: "Confirm New Mobile Number",
  mobile_no: "Mobile Number",

  current_email: "Current Email Address",
  new_email: "New Email Address",
  conf_new_email: "Confirm New Email",

  email: "Email Address",
  title_fgt_uid: "Forgot User ID",
  title_fgt_pwd: "Forgot Password",
  title_fgt_pin: "Forgot PIN",
  title_fgt_tpin: "Forgot Transaction PIN",
  ok_txt: "OK",
  new_pin: "Enter new PIN",
  conf_new_pin: "Confirm new PIN",
  enterHere: "Enter Here",
  error_already_login: "you have already set a primary device. If you want to login on other device, you have to complete new app login process. Do you want to continue?"

};
