export default {
  language_english: 'English',
  language_bangla: 'বাংলা',
  login: 'প্রবেশ করুন',
  next: 'পরবর্তী',
  user_ID: 'ব্যবহারকারীর আইডি লিখুন',
  passwordTxt: 'পাসওয়ার্ড লিখুন',
  signup: 'নিবন্ধন করুন',
  fgt_pwd_uid: 'ব্যবহারকারী আইডি বা পাসওয়ার্ড ভুলে যান',
  acc_no: "Enter Account Number",
  acc_name: "Enter Account Name",
  conf_mobile: "Confirm Mobile Number",
  conf_email: "Confirm Email Address",
  user_id_enter: "Enter User ID",
  user_id: "User ID",
  preferred_user_id: "Preferred User ID",
  read_term:"I have read and agree to the",
  term_condition: "terms and conditions",
  otp_type: "OTP Type",
  sms_txt:"SMS",
  email_txt:"Email",
  both_txt: "both",
  provide_card:"Please provide your debit card information",
  mmyy_txt:"MM / YY",
  enter_pin:"Enter PIN",
  et_father_name: "Enter Name of Father",
  et_mother_name:"Enter Name of Mother",
  et_dob:"Date Of Birth",
  et_last_trans:"Enter Last Transaction Date",
  et_last_trans_amount:"Enter Last Transaction Amount",
  et_set_user_id:"Set User ID",
  er_set_pwd:"Set Password",
  submit_txt:"Submit"
};
