import {Text} from "react-native";
import React from "react";

export default {
    language_english: "English",
    language_bangla: "বাংলা",
    login: "Login",
    save: "Save",
    next: "Next",
    user_ID: "Enter User ID",
    conf_user_ID: "Confirm User ID",
    login_pin:"Login Pin",
    passwordTxt: "Enter Password",
    new_pass_txt: "Enter new password",
    new_trans_pin_txt: "Enter new transaction pin",
    conf_new_trans_pin_txt: "Confirm new transaction pin",
    conf_new_pass_txt: "Confirm new password",
    signup: "Sign up",
    fgt_pwd_uid: "Forgot User ID or Password?",
    fgt_uid: "Forgot User ID?",
    fgt_pwd: "Forgot Password?",
    fgt_pin: "Forgot PIN?",
    alias: "Enter Alias",
    transactionPin: "Set Transaction PIN",
    conf_trans_pin: "Confirm Transaction PIN",
    loginPin: "Set Login PIN",
    et_pin: "Enter PIN",
    et_card_pin: "Enter card PIN",
    conf_loginPin: "Confirm Login PIN",
    acc_no: "Enter Account Number",
    card_no: "Enter Card Number",
    acc_name: "Account Name",
    donot_have_act: "Don't have bank account yet?",
    open_account: "Open Account",
    creditcard_name: "Enter Credit Card Name",
    prepaidcard_name: "Enter Prepaid Card Name",
    mobile: "Mobile Number",
    conf_mobile: "Confirm Mobile Number",
    conf_email: "Confirm Email Address",
    user_id_enter: "Enter User ID",
    user_id: "User ID",
    preferred_user_id: "Preferred User ID",
    read_term: "I have read and agree to the ",
    term_condition: "terms and conditions",
    term_condition_title: "Terms and Conditions",
    otp_type: "OTP Type",
    login_type: "Select Login Preference",
    language_type: "Select Language Preference",
    sms_txt: "SMS",
    email_txt: "Email",
    both_txt: "both",
    provide_card: "Please provide your debit card information",
    mmyy_txt: "Card expiry MM / YY",
    mmyy: "MM / YY",
    enter_pin: "Enter Card PIN",
    et_father_name: "Enter Name of Father",
    et_mother_name: "Enter Name of Mother",
    et_dob: "Date Of Birth",
    et_last_trans: "Enter Last Transaction Date",
    et_last_trans_amount: "Enter Last Transaction Amount",
    et_set_user_id: "Set User ID",
    er_set_pwd: "Set Password",
    er_otpPin: "Enter received OTP",
    et_transPin: "Enter transaction PIN",
    pwd: "Password",
    submit_txt: "Submit",
    otp_sent_txt: "Get OTP",
    view_balance:"View Balance",
    new_pwd_txt: "New Password",
    new_pin_txt: "New Pin",
    confirm_pwd_txt: "Confirm Password",
    confirm_pin_txt: "Confirm New Pin",
    prepaid_card: "Using Prepaid Card",
    credit_card: "Using Credit Card",
    using_act_no: "Using Account Number",

    with_prepaid_card: "Sign up with Prepaid Card",
    with_credit_card: "Sign up with Credit Card",
    with_act_no: "Sign up with Account Number",

    provide_info: "Please provide below information",
    provide_debit_card: "Please provide your debit card information",
    provide_credit_card: "Please provide your credit card information",
    provide_prepaid_card: "Please provide your prepaid  card information",

    deposit_account: "Deposit Accounts",
    summary_account: "Account Summary",
    fd: "Fixed Deposit",
    fundsTransfer: "Fund Transfer",
    cheque: "Cheque Details",
    cards: "Card\nDetails",
    other_services: "Other Services",

    loan: "loan",
    loan_accounts: "Loan Accounts",
    loan_scheduler: "Loan Scheduler",
    loan_against_deposit: "Loan Against Deposit",
    loan_interest_certificate: "Loan Interest Certificate",

    personalize_profile: "Personalise Profile",
    change_pwd: "Change Password",
    change_login_pin: "Change Login PIN",
    change_transaction_pin: "Change Transaction PIN",
    slogan: "Dear customer, Welcome to CityTouch Mobile Banking. For help Call: ",
    new_login_pin:"New Login PIN",
    conf_new_login_pin:"Confirm New Login PIN",

    fd_accounts: "FD accounts",
    new_fd_accounts: "New FD",


    cheque_book_details: "Cheque Book Details",
    cheque_status: "Cheque Status",
    cheque_book_request: "Cheque Book ApiRequest",
    cheque_book_request_detail: "Cheque Book ApiRequest Details",
    cheque_request_stop: "Cheque Stop ApiRequest",
    cheque_intimation: "Cheque intimation(Positive Pay)",
    view_cheque_intimation: "View Cheque intimation(Positive Pay)",


    current_saving: "Current Saving Accounts",
    term_deposit: "Term Deposits",
    credit_account: "Credit Card Accounts",

    present_address: "Enter your present address",
    communication_address: "Enter your Communication address",
    numberVal: "Enter document number",
    select_file: "Choose File",
    update: "Update",
    cancel: "Cancel",

    current_mobile_no: "Current Mobile Number",
    new_mobile_no: "New Mobile Number",
    mobile_no: "Mobile Number",

    current_email: "Current Email Address",
    new_email: "New Email Address",
    email: "Email Address",
    title_fgt_uid: "Forgot User ID",
    title_fgt_pwd: "Forgot Password",
    title_fgt_pin: "Forgot PIN",
    title_fgt_tpin: "Forgot Transaction PIN",
    ok_txt:"OK",
    new_pin:"Enter new PIN",
    conf_new_pin:"Confirm new PIN",

    error_already_login:"you have already set a primary device. If you want to login on other device, you have to complete new app login process. Do you want to continue?"

};
