import React from "react";
import Beneficiary from "../screens/Trasfer/Beneficiary/Beneficiary";

export default {
    language_english: "EN",
    language_bangla: "বাংলা",
    login: "Login",
    save: "Save",
    submit: "Submit",
    accept: "Accept",
    decline: "Decline",
    continue_txt: "Continue",
    next: "Next",
    confirm: "Confirm",
    user_ID: "Enter Your User ID",
    new_signup: "New in CityTouch?",
    sign_up_now: "Sign up now!",
    fgt_uid_pwd_pin: "Forgot User ID or Password or PIN ?",
    right_reserved: "All rights reserved. Copyright @2021 The City Bank Limited V 1.0",
    faqs: "FAQs",
    atm_branch: "ATM & Branch",
    info: "Info",
    privacy: "Privacy",
    contact: "Contact",
    select_contact_type: "Select Contact Type",
    select_credential_type: "Select Credential Type",
    select_actNo: "Select Account Number",
    credentialDetails: "Credential Details",
    selectionType: "Selection Type *",
    selectType: "Select Type",
    selectActType: "Select Account Type",
    type_act: "Type of Account *",
    changeIn: "Change in",
    actNo: "Account Number",
    actName: "Account Name",
    actNo_here: "Enter account number here",
    errorActNo: "Please enter account number",
    selectCard: "Select Card",
    transactionPin: "Transaction PIN",
    loginPin: "Login PIN",
    setLoginPIn: "Set Login PIN",
    enterCardPin: "Card PIN",
    enterExpiry: "Expiry Date",
    enterCardExpiry: "Select Card Expiry Date",
    enterPinHere: "Enter PIN here",
    otpType: "OTP Type:",
    back_txt: "Back",
    mark_field_mandatory: "Marked fields are mandatory",
    noRecord: "No Records Found",
    ok: "OK",
    passwordTxt: "Enter Your Password",
    expiryDate: "Enter Expiry Date here",
    credit_card_no: "Card Number",
    cardName: "Card Name",
    cardHolderName: "Card Holder Name",
    enter_card_no: "Enter Card Number here",
    otp: "OTP",
    otp_txt: "One Time Password",
    otp_sent: "Sent OTP",
    otp_description: "Please enter the OTP sent to your registered mobile/email ",
    otp_fgt_pwd: "to process forgot password",
    otp_fgt_pin: "to process forgot PIN",
    otp_fgt_uid: "to process forgot User ID",
    otp_change_tPin: "to process change transaction pin",
    otp_activate: "to activate Citytouch Digital Banking Service",
    otp_signup: "to process registration in Citytouch Digital Banking Service",
    otp_pwd: "to change password in Citytouch Digital Banking Service",
    otp_mobile: "to change mobile number in Citytouch Digital Banking Service",
    otp_email: "to change email address in Citytouch Digital Banking Service",

    otp_input_placeholder: "Enter 4 Digit One Time Password(OTP)",
    dnReceiveOTP: "Did not receive your OTP? ",
    sendAgain: "Send Again",
    termsCondition: "Terms and Conditions",
    emailAddress: "Email Address",
    mobileNo: "Mobile Number",
    sms: "SMS",
    email: "EMAIL",
    otpViaMob: "You will receive an One Time Password (OTP) via SMS to Mobile Number: ",
    otpViaEmail: "You will receive an One Time Password (OTP) via Email to Email Address: ",
    otpViaBoth: "You will receive an One Time Password (OTP) via both Email and SMS ",
    register_title: "Citytouch Online Registration",
    signupWithAccount: "SIGN UP WITH ACCOUNT",
    signupWithCard: "SIGN UP WITH CREDIT/PREPAID CARD",
    welcome_signup: "Welcome to CityTouch Online Registration process. Please enter your ",
    accountNo: "account Number",
    cardNoInput: "card Number",
    cardDetails: "card details",
    debitCard: "debit card details",
    debitCardNo: "Debit card Number",
    errDebitCard: "Please enter 16 digits debit card details",

    provideDetails: "Welcome to CityTouch Online Registration process. Please provide below details.",
    account: "Accounts",
    city_pay: "CityPay",
    qrId: "QR ID",
    et_qr: "Enter QR ID here",
    errorQRId: "Please enter QR ID",
    more: "More",
    payments: "Payments",
    transfer: "Transfer",
    goodEvening: "Good Evening, ",
    avail_balance: "Available Balance",
    view_balance: "View Balance",
    fatherName: "Father Name",
    errorFatherName: "Please Father Name",
    motherName: "Mother Name",
    et_father_name: "Enter Father Name",
    et_mother_name: "Enter Mother Name",
    errorMotherName: "Please enter mother name",
    et_dob: "Date Of Birth",
    select_dob: "Enter Date of Birth",
    etTransPin: "Please ",
    yes_txt: "Yes",
    no_txt: "No",
    user_id: "User ID",
    user_id_enter: "Enter User ID here",
    conf_mobile: "Confirm Mobile Number",
    conf_email: "Confirm Email Address",
    setPwdTxt: "Set Password",
    etPasswordTxt: "Enter Password here",
    enterTransactionPin: "Enter Transaction PIN",
    errTransactionPin: "Please enter transaction pin",
    errTConfPin: "Confirm new transaction pin mismatch with new transaction pin",
    last_trans_date: "Last Transaction Date",
    last_trans_amount: "Last Transaction Amount",
    personalise_profile: "Personalise Profile",
    change_contact: "Change Contact Details",
    change_login_password: "Change Login Password",
    change_login_pin: "Change Login PIN",
    change_Credential: "Change Credentials",
    change_transaction_pin: "Change Transaction PIN",
    upload_documents: "Upload Supporting Document",
    err_upload_documents: "Please upload  supporting document",
    upload_docs: "Upload Document",
    withdrawChk: "Withdrawn",
    dateTitle: "Date",
    typeTitle: "Type",
    current_balance: "Current Balance",
    amountTitle: "Amount",
    recent_trans: "Recent Transactions",
    descriptionTitle: "Description",
    depositChk: "Deposit",
    conf_loginPin: "Confirm Login PIN",
    customerName: "Customer Name",
    changeFor: "Change",
    login_configure_profile: "Login Configure Profile",
    config_information: "Please configure below information.",
    alias: "Alias",

    et_alias: "Enter Alias here",
    set_transaction_pin: "Set Transaction Pin",
    Transaction_Pin: "Transaction Pin",
    Confirm_Pin: "Confirm Transaction Pin",
    new_pin_txt: "New PIN",
    et_new_pin_txt: "Enter New Pin",
    errorNewPIN: "Please enter 6 digits new pin",
    errorNewConfPIN: "Confirm new pin should same as new pin",
    errorNewPwd: "Please enter new password",
    errorNewConfPwd: "Confirm new password should same as new password",
    errorNewMobNo: "Please enter new mobile number",
    errorMobConfNo: "Confirm new mobile number should same as new mobile number",
    errorEmail: "Please enter new Email",
    errorConfEmail: "Confirm new email should same as new Email",
    confirm_pin_txt: "Confirm New Pin",
    et_confirm_pin_txt: "Enter Confirm New Pin",
    et_confirm_pwd_txt: "Enter Confirm New Password",
    open_account: "Open Account",
    type_contact: "Contact Type *",
    type_credential: "Credential Type *",
    LoginWith: "Login With User ID?",
    PINLogin: "PIN Login",
    PinNumber: "Enter Your PIN Number",
    errSelRequest: "Please select request",
    invalidFatherName: "Invalid Father Name",
    invalidMotherName: "Invalid Mother Name",
    invalidDob: "Invalid Date of Birth",
    Language_M: [
        {label: "English", value: 0},
        {label: "বাংলা", value: 1},
    ],
    Language_P: "Language Preference",
    Login_W: "Login With",
    Login_M: [
        {label: "Password", value: 0},
        {label: "Pin", value: 1},
        {label: "Biometric", value: 2},
    ],

    LoginWithoutBio: [
        {label: "Password", value: 0},
        {label: "Pin", value: 1},
    ],

    contactList: [
        {label: "Change Mobile Number", value: 0},
        {label: "Change Email Address", value: 1},
    ],

    credentialList: [
        {label: "Change Login Password", value: 0},
        {label: "Change Mobile PIN", value: 1},
    ],

    DocumentRequiredForArr: [
        {label: "Change Mobile Number", value: 0},
        {label: "Change Email Address", value: 1},
    ],

    supportDocument: "Supporting Document",
    selectDocument: "Select the supporting document",
    documentNo: "Document Number",
    errDocumentNo: "Please enter document number",
    documentTypeArr: [
        {label: "NID", value: 1},
        {label: "Rental Deed", value: 2},
        {label: "Utility Bill Copy", value: 3},
        {label: "Property Purchase Document", value: 4},
        {label: "Business Card", value: 5},
        {label: "Passport", value: 6},
        {label: "Driving Licence", value: 7},
    ],
    loginFinger: "Login using Fingerprint",
    placeFinger: "Place your finger on fingerprint scanner to login",
    invalidEmail: "Invalid email address",
    invalidMobile: "Invalid Mobile Number",

    /*success messages*/
    success_fgt_uid: "User id has been sent via SMS/Email",
    success_msg: "Successfully done",
    success_saved: "Successfully Saved",
    success_updated: "Successfully updated",
    success_register: "Successfully Registered",


    /*error message*/
    require_user_id: "User ID is Required",
    require_length_user_id: "Length should be minimum 8",
    min_user_id: "User ID should be combination of digits and letters",
    require_pwd: "Password is Required",
    cityTouchUserId: "CityTouch User ID",
    requireUserId: "CityTouch User ID is Required",
    enterUserId: "Enter User ID here",
    deviceChangeTxt: "You will be logged out from all other devices. From now on this will be your primary device. Do you want to continue.",
    invalidCredential: "Invalid UserId or Password",
    invalidUid: "Invalid cityTouch user id",
    require_mobile: "Mobile Number is Required",
    require_email: "Email Address is Required",
    email_not_valid: "Invalid Email Address",
    maxOneMB: "Maximum 1 MB size of file allowed",
    max200KB: "Maximum 200 KB size of image allowed",
    digits4TransPin: "Please set 4 digits transaction pin",
    digits6LoginPin: "Please set 6 digits login pin",
    errConfirmTransPin: "Confirm transaction pin should be same as transaction pin",
    errConfirmLoginPin: "Confirm login pin should be same as login pin",
    errValidPin: "Please enter valid Login PIN",
    errValidType: "Please select type",
    errActNo: "Please enter 13 digits account number",
    errBkash: "Please enter valid bKash account number",
    errTransPin: "Please enter 4 digits PIN",
    errCardNo: "Please enter valid card number",
    errExpiryDate: "Please select expiry date",
    errCardPin: "Please enter 4 digits card PIN",
    errorUserId: "Please enter User ID ",
    errOTP: "Please enter 4 digit OTP",
    errorPwd: "Please enter password",
    errorpassword: "Your password should contain at least one character of a-z, A-Z and 0-9",
    errorMother: "Please enter Mother Name",
    errorDob: "Please select Date Of Birth",
    errorTransDate: "Please enter Transfer Date",
    errorTransAmt: "Please enter Transfer Amount",
    errAccountMatch: "Account Number does not match with given CityTouch User ID",
    errCardMatch: "Card Number does not match with given CityTouch User ID",
    /*confirmation message*/
    logout_confirm: "Are you sure want to Logout?",
    exitConfirm: "Are you sure want to exit from App?",
    select_date: "Select Date",
    wrongMobile: "Please enter correct mobile number",
    maskingMobile: "Please enter the missing letters of mobile",
    maskingEmail: "Please enter the missing letters of email",
    wrongEmail: "Please enter correct email address",
    errorLUserID: "Length of user id should be 8 to 12 characters.",
    errorAUserID: "User id can be character or combination of alphanumeric and special characters.",
    errorTerm: "Please accept term and conditions",

    /*arrays*/
    optionTypeArr: [
        {key: "0", label: "Forgot User ID", value: 0},
        {key: "1", label: "Forgot Password", value: 1},
        {key: "2", label: "Forgot PIN", value: 2},
    ],

    accountTypeArr: [
        {key: "0", label: "Account Number", value: 0},
        {key: "1", label: "Credit/Prepaid Card Number", value: 1}
    ],

    changeInArr: [
        {key: "A", label: "Account", value: 0},
        {key: "C", label: "Card", value: 1}
    ],
    otp_props_mobile: [
        {label: "SMS", value: 0},
    ],
    otp_props_email: [
        {label: "EMAIL", value: 1},
    ],
    otp_props: [
        {label: "SMS", value: 0},
        {label: "Email", value: 1}
    ],

    userIdOption: [
        {label: "User ID", value: 0},
        {label: "Preferred User ID", value: 1}
    ],

    transfer_props: [
        {id: "cityBankAcct", title: "City Bank Account", icon: require("../resources/images/ic_city_bank_account.png")},
        {id: "otherBankAcct", title: "Other Bank Account", icon: require("../resources/images/contact_icon.png")},
        {id: "cashByCode", title: "Cash By Code", icon: require("../resources/images/case_by_code.png")},
        {id: "emailTransfer", title: "Email Transfer", icon: require("../resources/images/email_transfer.png")},
        {id: "transferToBkash", title: "Transfer To Bkash", icon: require("../resources/images/transfer_to_bkash.png")},
        {
            id: "beneficiaryManagement",
            title: "Beneficiary Management",
            icon: require("../resources/images/beneficiary_management.png")
        },
        {
            id: "favoriteTransfer",
            title: "Favorite Transfers",
            icon: require("../resources/images/ic_facourite_transfer.png")
        },
        {id: "transferHistory", title: "Transfer History", icon: require("../resources/images/ic_transfer_istory.png")}
    ],
    payments_props: [
        {id: "MobileRecharge", title: "Mobile Recharge", icon: require("../resources/images/ic_mobile_recharge.png")},
        {id: "CityCreditCard", title: "City Credit Card", icon: require("../resources/images/ic_city_credit_card.png")},
        {
            id: "ValueAddedServices",
            title: "Value Added Services",
            icon: require("../resources/images/ic_value_added_services.png")
        },
        {
            id: "VisaInstantPayment",
            title: "Visa Instant Payment",
            icon: require("../resources/images/ic_visa_instant_payments.png")
        },
        {
            id: "BeneficiaryManagement",
            title: "Beneficiary Management",
            icon: require("../resources/images/beneficiary_management.png")
        },
        {
            id: "FavoritePayments",
            title: "Favorite Payments",
            icon: require("../resources/images/ic_facourite_transfer.png")
        },
        {
            id: "PaymentHistory",
            title: "Payment History",
            icon: require("../resources/images/ic_transfer_istory.png")
        },
        {}
    ],


    conf_user_ID: "Confirm User ID",
    login_pin: "Login Pin",

    pwd_txt: "New Password",
    new_pass_txt: "Enter new password",
    new_trans_pin_txt: "Enter new transaction pin",
    conf_new_trans_pin_txt: "Confirm new transaction pin",
    conf_new_pass_txt: "Confirm new password",
    signup: "Sign up",
    fgt_pwd_uid: "Forgot User ID or Password?",
    fgt_uid: "Forgot User ID?",
    fgt_pwd: "Forgot Password?",
    fgt_pin: "Forgot PIN?",

    conf_trans_pin: "Confirm Transaction PIN",

    et_pin: "Enter PIN",
    et_card_pin: "Enter card PIN",
    acc_no: "Enter Account Number",
    card_no: "Enter Card Number",

    donot_have_act: "Don't have bank account yet?",

    creditcard_name: "Enter Credit Card Name",
    prepaidcard_name: "Enter Prepaid Card Name",
    mobile: "Mobile Number",


    preferred_user_id: "Preferred User ID",
    read_term: "I have read and agree to the ",
    term_condition: "terms and conditions",
    term_condition_title: "Terms and Conditions",
    otp_type: "OTP Type",
    login_type: "Select Login Preference",
    language_type: "Select Language Preference",
    sms_txt: "SMS",
    email_txt: "Email",
    both_txt: "both",
    provide_card: "Please provide your debit card information",
    mmyy_txt: "Card expiry MM / YY",
    mmyy: "MM / YY",
    enter_pin: "Enter Card PIN",


    et_set_user_id: "Set User ID",
    er_set_pwd: "Set Password",
    er_otpPin: "Enter received OTP",
    et_transPin: "Enter transaction PIN",
    pwd: "Password",
    submit_txt: "Submit",
    otp_sent_txt: "Get OTP",

    new_pwd_txt: "New Password",
    act_card_no: "Account Number/Card Number",
    sel_act_card_no: "Select Account Number/Card Number",
    confirm_pwd_txt: "Confirm Password",
    select_request: "Select Request",
    prepaid_card: "Using Prepaid Card",
    credit_card: "Using Credit Card",
    using_act_no: "Using Account Number",

    with_prepaid_card: "Sign up with Prepaid Card",
    with_credit_card: "Sign up with Credit Card",
    with_act_no: "Sign up with Account Number",

    provide_info: "Please provide below information",
    provide_debit_card: "Please provide your debit card information",
    provide_credit_card: "Please provide your credit card information",
    provide_prepaid_card: "Please provide your prepaid  card information",

    deposit_account: "Deposit Accounts",
    summary_account: "Account Summary",
    fd: "Fixed Deposit",
    fundsTransfer: "Fund Transfer",
    cheque: "Cheque Details",
    other_services: "Other Services",

    loan: "loan",
    loan_accounts: "Loan Accounts",
    loan_scheduler: "Loan Scheduler",
    loan_against_deposit: "Loan Against Deposit",
    loan_interest_certificate: "Loan Interest Certificate",

    personalize_profile: "Personalise Profile",
    change_pwd: "Change Password",
    change_transaction_pin: "Change Transaction PIN",
    slogan: "Dear customer, Welcome to CityTouch Mobile Banking. For help Call: ",
    new_login_pin: "New Login PIN",
    conf_new_login_pin: "Confirm New Login PIN",

    fd_accounts: "FD accounts",
    new_fd_accounts: "New FD",


    cheque_book_details: "Cheque Book Details",
    cheque_status: "Cheque Status",
    cheque_book_request: "Cheque Book ApiRequest",
    cheque_book_request_detail: "Cheque Book ApiRequest Details",
    cheque_request_stop: "Cheque Stop ApiRequest",
    cheque_intimation: "Cheque intimation(Positive Pay)",
    view_cheque_intimation: "View Cheque intimation(Positive Pay)",


    current_saving: "Current Saving Accounts",
    term_deposit: "Term Deposits",
    credit_account: "Credit Card Accounts",

    present_address: "Enter your present address",
    communication_address: "Enter your Communication address",
    numberVal: "Enter document number",
    select_file: "Choose File",
    update: "Update",
    cancel: "Cancel",

    current_mobile_no: "Current Mobile Number",
    new_mobile_no: "New Mobile Number",
    conf_new_mobile_no: "Confirm New Mobile Number",
    mobile_no: "Mobile Number",

    current_email: "Current Email Address",
    new_email: "New Email Address",
    conf_new_email: "Confirm New Email",

    email: "Email Address",
    title_fgt_uid: "Forgot User ID",
    title_fgt_pwd: "Forgot Password",
    title_fgt_pin: "Forgot PIN",
    title_fgt_tpin: "Forgot Transaction PIN",
    ok_txt: "OK",
    new_pin: "Enter new PIN",
    conf_new_pin: "Confirm new PIN",
    enterHere: "Enter Here",
    error_already_login: "you have already set a primary device. If you want to login on other device, you have to complete new app login process. Do you want to continue?",

    /*    registartion error*/
    require_transaction_p: "Transaction Pin is required",


    credit_card_det: "Credit Card Details",
    card_number: "Card Number",
    statement_date: "Statement Due Date",
    payment_date: "Payment Date",
    last_balance: "Last Outstanding Balance",
    minimum_payment: "Minimum Payment Due",
    previous_bal: "Previous Balance",
    interest_charge: "Interest Charge",
    pay_now: "Pay Now",
    unbilled: "UNBILLED",
    current: "CURRENT",
    bdt: "BDT",
    visa: "VISA",
    date: "DATE",
    amount: "AMOUNT",
    total_credit: "Total Credit Line",
    credit_available: "Credit Available",
    outstanding_bal: "Outstanding",

    /*Transfer Category screen message*/
    transfer_title: "Transfer Category",
    transfer_subtitle: "Please Select One of the Category",
    transfer_owncbl_acct: "Transfer within own CBL Accounts",
    transfer_othercbl_acct: "Transfer within other CBL Accounts",
    transfer_otherbank_acct: "Transfer within other Bank Accounts",
    transfer_bkash: "Transfer to bkash",
    cash_by_code: "Cash By Code",

    /*Transfer History screen message*/
    description: "Description",
    amount: "Amount",
    transfer_history: "Transfer History",

    /*beneficiary management message*/
    add_beneficiary: "Add Beneficiary",
    view_beneficiary: "Beneficiary",
    delete_beneficiary: "View/Delete Beneficiary",
    beneficiary_management: "Beneficiary Managements",

    type_transfer: "Type Of Transfer *",
    select_type_transfer: "Select Transfer Type",
    select_beneficiary_type: "Select Beneficiary Type",
    transferTypeArr: [
        {key: "0", label: "bKash Fund Transfer", value: 0},
        {key: "1", label: "City Bank Account", value: 1},
        {key: "2", label: "Other Bank Account", value: 2},
        {key: "3", label: "Transfer By Email", value: 3},
        /* {key: "4", label: "Other Credit Card", value: 4},
         {key: "5", label: "City Bank Credit Card", value: 5},*/
    ],

    TypeOfTransferArr: [
        {key: "0", label: "Transfer Within City Bank", value: 0},
        {key: "1", label: "Transfer Other Bank", value: 1},
        {key: "2", label: "Transfer Within City Bank", value: 2},
        {key: "3", label: "Transfer Other Bank", value: 3}
    ],
    notAvailable: "Not available",
    add_beneficiary_wcb: "Add Beneficiary-Within City Bank",
    manage_beneficiary_wcb: "Beneficiary-Within City Bank",
    add_beneficiary_mfs: "Add Beneficiary-bKash",
    manage_beneficiary_mfs: "Beneficiary-bKash",
    nick_name: "Nick Name",
    account_holder_name: "Account Holder Name",
    currency: "Currency",
    type_act: "Type Of Account",
    beneficiary_mobile_number: "Beneficiary Mobile Number",
    beneficiary_Email_Address: "Beneficiary Email Address",
    et_placeholder: "Please fill up",
    acc_number: "Account Number",
    beneficiary_mo_number: "Beneficiary Mobile Number",
    et_name_number: "Enter name or number",
    scanQrCode: "Scan QR Code",
    require_nickname: "Nick Name is Required",
    require_accnumber: "Account Number is required",
    require_valid_actNumber: "Invalid Account Number",
    invalid_cardNumber: "Invalid Card Number",
    require_cardname: "Card Holder Name is Required",
    require_actName: "Account Holder Name is Required",
    require_cardnumber: "Card number is required",
    require_bkash: "Bkash Account is required",
    require_name: "Name is required",
    require_bname: "Beneficiary Name is required",
    require_email: "Email Address is required",
    add_beneficiary_wob: "Add Beneficiary-Other Bank",
    manage_beneficiary_wob: "Beneficiary-Other Bank",
    add_beneficiary_email: "Add Beneficiary-Email",
    manage_beneficiary_email: "Beneficiary-Email",
    type_bank: "Bank Name",
    select_bank_type: "Select Bank Name",
    type_district: "District Name",
    select_type_account: "Select Account Type",
    select_district_type: "Select District Name",
    select_branch_type: "Select Branch Name",
    error_select_bank_name: "Please Select Bank Name",
    error_select_district_name: "Please Select District Name",
    error_select_branch_name: "Please Select Branch Name",
    error_select_beneficiary_type: "Please Select Beneficiary Type",
    error_select_from_type: "Please Select From Account",
    error_select_credit_card: "Please Select Credit Card",
    error_select_nickname: "Please Select Nickname",
    error_select_operator: "Please Select Operator",
    errorSelectCard: "Please select card",
    errorSelMFSVal: "Please select MFS",
    error_select_reason: "Please Select Reason",
    type_Branch: "Branch Name",
    select_branch_name: "Select Branch Name",

    notes: "Notes",
    note: "Note:",

    add_beneficiary_transfer: "Add Beneficiary-Transfer to bkash",
    bkash_account: "bkash Account",
    please_enter: "Please enter here",

    name: "Name",
    b_name: "Enter Beneficiary Name Here",
    b_email: "Enter Beneficiary Email",
    add_beneficiary: "Add Beneficiary",

    /*Transfer to bkash screen*/
    transfer_bkash: "Transfer to bkash",
    select_nickname: "Select Nickname",
    bkash_account: "bkash Account",
    bkash_name: "Name",
    fromAccount: "From Account",
    bkash_select_acct: "Select Account",
    available_bal: "Available Balance",
    transfer_amount: "Transfer Amount",
    services_charge: "Services Charge",
    grand_total: "Grand Total",
    remarks: "Remarks",
    selectNickType: "Select Nickname",
    nickTypeArr: [
        {key: "0", label: "Ebad Vai", value: 0},
        {key: "1", label: "Masvm", value: 1},
        {key: "2", label: "Onn bKash", value: 2}
    ],
    cardNumber: [{key: "0", label: "1234567890123456", value: 1234567890123456}, {
        key: "1",
        label: "4567890123456123",
        value: 4567890123456123
    }],

    /*error message*/
    errAmt: "Require transfer amount",
    errTransferAmt: "Minimum transfer limit is",
    errMaxTransferAmt: "Maximum transfer limit is",
    errRemarks: "Remarks is Required",
    errPrepaidStaff:"Transfer from prepaid card to staff account is not allowed",
    /*Cash By Code message*/
    cashbycode: "Cash By Code",
    select_debit_card: "Select Debit Card",
    select_card_title: "Select Card  to Generate",
    select_card: "Select Card",
    cash_select_acct: "Debit Card",
    cash_amount: "Amount",
    bkash_otp_props: [
        {label: "Screen Display", value: 0},
        {label: "SMS", value: 1},
        {label: "Email", value: 2},
    ],
    case_code_via: "Case Code Via",

    /*error message*/
    error_amount: "Total Amount is Required",
    error_mobile: "Mobile Number is Required",

    /*Fund transfer screen*/
    fund_transfer: "Fund Transfer",
    currency: "Currency",
    TransferType: "Transfer",
    transfer_pay_props: [
        {label: "Pay Now", value: 0},
        {label: "Schedule Payment", value: 1}
    ],
    select_from_account: "Select From Account",
    to_account: "To Account",
    vat: "VAT",
    select_to_acct: "Select To Account",
    to_acct: "To Account",
    balanceTypeArr: [
        {key: "0", label: "2000", value: 0},
        {key: "1", label: "5000", value: 1},
        {key: "2", label: "10000", value: 2},
        {key: "3", label: "20000", value: 3},
        {key: "4", label: "50000", value: 4}
    ],
    ownAccount: "OWN ACCOUNT",
    cityAccount: "CITY ACCOUNT",
    payment_date: "Payment Date",
    select_payment_date: "Select Payment Date",
    Frequency: "Frequency",
    select_payment: "Select Payment Frequency",
    number_of_payment: "Number Of Payment",
    payment_array: [{key: "0", label: "Monthly", value: 1234567890123456},
        {key: "1", label: "Quarterly", value: 4567890123456123},
        {key: "1", label: "HalfYearly", value: 4567890123456123},
        {key: "1", label: "Yearly", value: 4567890123456123}
    ],

    error_payment_ammt: "Payment Amount is Required",
    error_less_ammt: "Transfer Amount should be greater then or equal to 500.",
    error_payment_date: "Select Payment Date",
    error_numberPayment: "Number of payment is Required",

    own_accountt: "OWN ACCOUNT",
    city_accountt: "CITY ACCOUNT",

    /*Transfer to bkash screen message*/
    other_bank_account_title: "Other Bank Account Fund Transfer",
    bank_name: "Bank Name",
    account_type: "Account Type",
    district_type: "District Name",
    branch_name: "Branch Name",
    other_bank_props: [
        {label: "BEFTN(Regular Transfer)", value: 0},
        {label: "RTGS(Instant Transfer)", value: 1},
        {label: "NPSB(Instant Transfer)", value: 2},
    ],
    transfer_mode: "Transfer Mode",

    /* Favorite Transfer screen message*/
    Donation: "Donation",
    transfer_bkash: "Transfer to bkash",

    favoriteTitle: "Swipe Right to left to Delete Favourite item",
    favorite_transferTitle: "Favorite Transfer",

    /* Email Transfer screen message*/
    send: "SEND",
    waiting: "WAITING",
    send_message: " You can transfer fund Email Transfer.",
    email: "Email",
    email_transfer: "Email Transfer",
    payment_amount: "Payment Amount",
    security_questions: "Security Questions",
    answer: "Answer (case sensitive)",
    security_pl_holder: "Enter Your Security Question",
    payment_amount_pl: "Enter Payment Amount Here",
    answer_pl: "Enter Your Answer",
    beneficiary_type: "Beneficiary",

    /*error message*/
    err_payment_amount: "Payment amount is required",
    err_security: "Enter Your Security Question",
    error_answer: "Enter Your Answer",

    update_beneficiary: "Update Beneficiary - Other Bank",
    select_txt: "Select",

    /*Select Beneficiary*/
    select_beneficiary: "Select Beneficiary",

    /*Mobile Recharge*/
    operatorType: "Operator",
    select_operator_type: "Select Operator",
    SelectOperator: "Select Operator",
    operatorsTypeArr: [
        {key: "0", label: "grameenphone", value: 0},
        {key: "1", label: "Banglink", value: 1},
        {key: "2", label: "Robi", value: 2},
        {key: "3", label: "Airtel", value: 3},
        {key: "4", label: "Teletalk", value: 4}
    ],
    mobileRecharge: "Mobile Recharge",
    phoneNumber: "Phone Number",
    connectionType: "Connection Type",
    connectionType_props: [
        {label: "Prepaid", value: 0},
        {label: "Postpaid", value: 1},
    ],
    fromAccount: "From Account",
    totalAmount: "Total Amount",
    totalServicesCharge: "Total Services Charge",
    grandTotal: "Grand Total",

    /*error message*/
    errPaymentAmount: "Payment Amount is Required",

    /*View Beneficiary Other Bank*/
    account_card_number: "Account/Card Number",
    account_card_name: "Account/Card Name",
    bank_name: "Bank Name",
    district_name: "District Name",
    branch_name: "Branch Name",
    account_Type: "Account Type",
    add_beneficiaryOtherBank: "Add Beneficiary - Other Bank",

    /*CityTouch Security verification*/
    cards: "Cards",
    select_card: "Select Cards",
    cardPin: "Card PIN",
    et_cardPlaceholder: " Enter Card Pin",
    add: "Add",
    security_verification: "CityTouch Security verification",
    errSecurity: "Can not be blank",
    transactionPin: "Transaction PIN",
    et_TransPlaceholder: "Enter PIN Here",
    errorTransactionPin: "Please enter 4 digit Transaction PIN",
    transactionTitle: "Enter Transaction PIN",

    /*notes*/


    notePin4Digits: "Your Transaction PIN should be 4 digits.",
    noteLock3Attempt: "Consecutive 3 wrong attempts will lock.",
    noteCallTPin: "Your Transaction PIN call 16243 to unlock.",
    fund_transfer_note1: "1.There is no found transfer restriction between your",

    fund_transfer_note2: "own account for account transaction.",
    fund_transfer_note3: "2.Credit card transfer limit:Minimum transferable.",
    fund_transfer_note4: "amount is BDT 500 and up to 50% of total available.",
    fund_transfer_note5: "BDT limit.",
    fund_transfer_note6: "3.Processing fee +VAT will be applicable",
    fund_transfer_note7: "4. Consecutive transaction in the same account will",
    fund_transfer_note8: "take 10 minutes of interval.",

    fund_transferCity_note1: "1.Maximum Transaction limit from CityTouch is BDT",
    fund_transferCity_note2: "5 lacs per day",

    other_bankAccount_note1: "1. Maximum transaction limit from CityTouch is BDT 5 lacs per day.",
    other_bankAccount_note2: "2. BEFTN: transfer request placed before 2:00 PM will",
    other_bankAccount_note3: "be executed on the. same working day and transfer request",
    other_bankAccount_note4: " placed after 2:00 PM will be executed on the next working day after 10.00 AM.",
    other_bankAccount_note5: "3. RTGS Available from 10:30 to 03:00 PM for instant.",
    other_bankAccount_note6: "transfer of 1 to 5 lacs within working day.Fee BDT 100 (VAT Inclusive)",
    other_bankAccount_note7: "4. NPSB: Transfer limit is BDT 5 lacs in 10 transaction",
    other_bankAccount_note8: " per day and maximum BDT 1 lacs per transaction",
    other_bankAccount_note9: "5. Credit card transfer limit: minimum transferable",
    other_bankAccount_note10: " amount is BDT is 500 and up to 50% of total available BDT limit.",
    other_bankAccount_note11: "6.Processing fee + Vat will be applicable",
    other_bankAccount_note12: "7.consecutive transaction in the same account will take 10 minutes of interval",

    beneficiary_otherBank_note1: "1. Beneficiary banks/branches should be capable to",
    beneficiary_otherBank_note2: "process RTGS/NPSB/BEFTN transaction.",
    beneficiary_otherBank_note3: "2. BEFTN(Ragular Transfer): Transaction Process",
    beneficiary_otherBank_note4: "before 10:30 PM,any amount up to 5 lacs. Transfer Processed",
    beneficiary_otherBank_note5: "through BEFTN whould be credited by next working day.the amount",
    beneficiary_otherBank_note6: "3. RTGS (instant transfer): Transactions processed",
    beneficiary_otherBank_note7: "before 10:30 PM,any amount up to 5 lacs must",
    beneficiary_otherBank_note8: "be between 1 lac to 5 lacs",
    beneficiary_otherBank_note9: "4. NPSB (instant transfer). transfer can be processed",
    beneficiary_otherBank_note10: "anytime.Transaction limit is BDT 2 lacs in 5 transaction",
    beneficiary_otherBank_note11: "per day and BDT 2 lacs in 5 transaction",
    beneficiary_otherBank_note12: "5. For NPSB transfer,while adding DBBL beneficiary,",
    beneficiary_otherBank_note13: "complete 13-digit account number will be required.",
    beneficiary_otherBank_note14: "in case of adding DBBL credit card,the digit 100001",
    beneficiary_otherBank_note15: "need to be added before the 13-digit card number.",

    transferTo_bkash_note1: "1. Transfer and transaction limit for a single bkash account.",
    transferTo_bkash_note2: "5 transaction per day and 25 per month. Transfer",
    transferTo_bkash_note3: "amount is BDT 50 to BDT 30000 per day and BDT 2 lacs per month.",
    transferTo_bkash_note4: "2. CityTouch to bkash transfer limit: Up to BDT 60000 per day.",
    transferTo_bkash_note5: "3. Credit card transfer limit: minimum transferable",
    transferTo_bkash_note6: "amount is BDT 500 and up to 50% of total available BDT limit.",
    transferTo_bkash_note7: "4. Processing fee +VAT will be applicable",
    transferTo_bkash_note8: "5. consecutive transfer in the same bkash account",
    transferTo_bkash_note9: "require minimum 10 minutes interval.",

    cashBy_code_notes1: "1. Minimum Transfer Amount: Tk.500 per transaction..",
    cashBy_code_notes2: "2. Maximum Transfer Amount: Tk. 100,000 per day.",
    cashBy_code_notes3: "3. Transfer amount should be 500 or multiple of 500 up to 20,000",


    email_transfer_note1: "1. An email transfer transaction will be valid for next 10 days.",
    email_transfer_note2: "2. Maximum transferable amount:BDT in 5 lacs per day",
    email_transfer_note3: "3. Generated transfer could be canceled anytime from \"Waiting\" Tab before withdrawing by the beneficiary.",
    email_transfer_note4: "Beneficiary has to answer the security questions. case sensitive.",

    mobile_recharge_note1: "1. Minimum recharge amount for postpaid connection",
    mobile_recharge_note2: "Tk.50/- and for prepaid Tk. 10/-.",
    mobile_recharge_note3: "2. Maximum recharge amount for postpaid connection",
    mobile_recharge_note4: "Tk.10000/- and for prepaid Tk. 1000/-.",
    mobile_recharge_note5: "3. only prepaid recharge is acceptable in Teletalk numbers.",
    mobile_recharge_note6: "4. Consecutive recharge in the same number require.",
    mobile_recharge_note7: "minimum 15 minutes interval.",
    mobile_recharge_note8: "if your recharge amount is equivalent to any trigger/bundle",
    mobile_recharge_note9: "pack amount, a data/minute/bundle pack will be activated",

    fixed_deposit_note1: "1. You can View the details of this FDR after 1(one)",
    fixed_deposit_note2: "working day of your request a CityTouch.",
    fixed_deposit_note3: "2. if  you select auto renewal options No for  fixed",
    fixed_deposit_note4: "Deposit- General then the entire amount will be transferred to",
    fixed_deposit_note5: "your respected account automatically after maturity",
    fixed_deposit_note6: "3. fixed Deposit beneficiary name would be same as ",
    fixed_deposit_note7: "respective account name.",
    fixed_deposit_note8: "4. Nominee of this fixed deposit (FD) would be same as",
    fixed_deposit_note9: "respective current/saving account.To change existing ",
    fixed_deposit_note10: "nomination,please visit your nearest branch.",
    fixed_deposit_note11: "FD opening date would be same as your instruction ",
    fixed_deposit_note12: "placement date at CityTouch.You can view the details of ",
    fixed_deposit_note13: "this FDR after 1 (one) working day from CityTouch or Branch. ",

    monthly_deposit_note1: "1. Nominee of this DPS will be same as respective ",
    monthly_deposit_note2: "current/saving account.To change nominee of your ",
    monthly_deposit_note3: "current/saving account please visit any of our Branches.",
    monthly_deposit_note4: "2. DPS beneficiary name would be same as respective account name",
    monthly_deposit_note5: "3. monthly DPS installment to be automatically realized",
    monthly_deposit_note6: "from your respective current/saving account.",
    monthly_deposit_note7: "4. you can view the details of this DPS after 1(one)",
    monthly_deposit_note8: "working day of your request at CityTouch.",
    monthly_deposit_note9: "5. If the monthly instalment remains unpaid for 4(four)",
    monthly_deposit_note10: "consecutive months DPS will be closed automatically",

    pay_order_notes1: "1. Pay order will be processed solely as per your provided information.",
    pay_order_notes2: "2. your pay order to be ready to collect from desired branch",
    pay_order_notes3: "by next available working day.",
    pay_order_notes4: "3. To cancel a pay order,please visit the pay order issued ",
    pay_order_notes5: "Branch",
    pay_order_notes6: "4. The bank shall not be liable or responsible for any ",
    pay_order_notes7: "incorrect/incomplete information provide by you",

    click_her: "click here to read positive pay instruction by ",
    click_her1: "Bangladesh Bank",

    positivePay_note1: "1. As per Bangladesh Bank Positive pay instruction is",
    positivePay_note2: "required for all interbank clearing cheques for personal",
    positivePay_note3: "account Tk.5 lacs & above and for other account Tk.1 lac & above.",
    positivePay_note4: "2. CityTouch only shows you the unclear cheque.",
    positivePay_note5: "3. in case of mismatch in cheque details. bank may call",
    positivePay_note6: " you to agree to the physical cheque information.",


    scanQrNote: "- SCAN the QR code displayed at the merchant counter.",
    card_block_notes1: "1. if you select stolen or lost option,your card will be",
    card_block_notes2: "permanently deactivated. To block temporarily you may",
    card_block_notes3: "chose restricted option",
    card_block_notes4: "2. call 16243 for a replacement request or to reactivate the card.",
    tagCreditTitle: "Please provide following information of your City Bank",
    tagCreditTitle1: "issue Credit Card that you want to tag with your City",
    tagCreditTitle2: "Touch Digital Banking",
    tagCreditBottom: "Can We Help?",
    call: "call: 16234(local)/+880-2-8331040",


    /*Credit Card Payment*/
    own_creditCardPayment: "OWN CREDIT CARD PAYMENT",
    other_creditCardPayment: "OTHER CREDIT CARD PAYMENT",
    creditCardTitle: "Credit Card Payment",
    creditCard: "Credit Card",
    selectCreditCard: "Select Credit Card",
    payment_Amount: "Payment Amount",
    payment_narration: "Payment Narration",
    minimum_paymentDue: "Minimum Payment Due",
    last_outstanding_bal: "Last Outstanding Balance",
    bdtType_props: [
        {label: "BDT", value: 0},
        {label: "USD", value: 1},
    ],
    card_holderName: "Card Holder Name",
    card_number: "Card Number",
    favorite_payment: "Favorite Payments",

    /*insurance Payments*/
    policy_number: "Policy Number",
    policyHolders_name: "Policy Holder's Name",
    insurancePaid: "Insurance Paid For",
    insuranceTypeArr: [
        {key: "0", label: "Premium", value: 0},
        {key: "1", label: "Application", value: 1},
        {key: "2", label: "Loan Repayment", value: 2},
        {key: "3", label: "Reinstatement", value: 3},
        {key: "4", label: "Balance Premium", value: 4},
        {key: "5", label: "APL Repayment", value: 5}
    ],
    selectInsurance: "Select Insurance Paid For",

    /*more screen*/
    settings: "My Settings",
    account_services: "Account Services",
    card_services: "Card Services",
    loan_services: "Loan Services",
    credential_management: "Credential Management",
    other_qr_feature: "Other Qr Feature",
    change_contact_details: "Change Contact Details",
    otp_lock_unlock: "Otp Lock/Unlock",
    online_purchase: "Online Purchase",
    enquiry: "Enquiry",
    rate_cityTouch: "Rate CityTouch",
    term_condition: "Terms And Conditions",

    /*my setting*/
    pin_code: "PIN code",
    user_id: "User ID",
    retina: "Retina",
    qr_merchant_payment: "QR Merchant payment",

    /*account srvices*/
    fixed_deposit: "Fixed Deposit",
    monthly_Dps: "Monthly DPS",
    pay_order: "Pay Order",
    positive_pay: "Positive Pay",
    cheque_book_management: "Cheque Book Management",
    tag_account_cityTouch: "Tag Account CityTouch",
    edit_account_preview: "Edit Account Preview",
    request_monitor: "Request Monitor",

    /*Card Services*/
    active_credit_card: "Active Credit Card",
    active_debit_card: "Active Debit Card",
    block_credit_card: "Block Credit Card",
    block_debit_card: "Block Debit Card",
    card_pin_reset: "Card PIN Reset",
    tag_credit_card: "Tag Credit Card In CityTouch",

    /*Loan Services*/
    quick_loan: "Apply for Quick Loan",
    loan_closure: "Loan Closure",
    request_monitor: "Request Monitor",
    emi_calculator: "EMI Calculator",

    /*Credential Management*/
    change_login_password: "Change Login Password",
    change_transaction_password: "Change Transaction PIN",
    forgot_transaction_password: "Forgot Transaction Password",
    change_mobile_pin: "Change Mobile PIN",

    /*Enquiry screen*/
    enquiry: "Enquiry",
    customer_details: "Customer Details",
    schedule_charges: "Schedule of Changes",
    products: "Products",
    submit_query: "Submit Query",
    atm_branch_search: "Atm & Branch Search",
    contact_call_center: "Contact Call Center",

    /*Credit Card Activation*/
    creditCard_title: "Credit Card Activation",
    select_card_number: "Select Card Number",
    select_expiry_date: "Select Expiry Date",
    selected_card: "Select Card",
    credit_card_no: "Credit Card Number",
    card_status: "Card Status",
    card_state: "Card State",
    card_holder_name: "Card Holder Name",
    card_type: "Card Type",
    expiry_date: "Expiry Date",
    cardTypeArr: [
        {key: "0", label: "376948*****9669/Alo Credit Card", value: 0},
        {key: "1", label: "474867****0655/AMEX/AGORA", value: 1},
        {key: "2", label: "376948*****9669/AMEX", value: 2},
    ],

    /*Debit Card Activation*/
    debit_card_activation: "Debit Card Activation",

    /*Block Credit Card*/
    card_block: "Reason For Card Block",
    select_reason: "Select Reason",
    cardBlockTypeArr: [
        {key: "0", label: "Restricted", value: 0},
        {key: "1", label: "Lost", value: 1},
        {key: "2", label: "Stolen", value: 2},
    ],

    /*card pin reset*/
    pin_change_reason: "PIN Change Reason",
    new_pin_number: "New PIN Number",
    confirm_pin_number: "Confirm PIN Number",
    pim_reason_placeholder: "Enter Reason",
    newPIn_placeholder: "Enter New Pin",
    confirmPin_placeholder: "Re-enter New Pin",
    error_pinChangeReason: "PIN Change Reason is Required",
    error_newPinNumber: "PIN Number is Required",
    error_confirmPinNumber: "Confirm PIN Number is Required",

    /*Tag Credit Card in CityTouch*/
    tagCredit: "Please",
    enter_Card_Number: "Enter Card Number",
    card_Member_Name: "Card Member Name",
    cardNo_placeholder: "Please Enter Card Number",
    error_card_number: "Card Number Is Required",


    /*CheckBook Management*/
    cheque_leaf_status: "Check Leaf Status",
    Cheque_stop_request: "Cheque Stop Request",
    cheque_book_request: "Cheque Book Request",
    cheque_book_request_status: "Cheque Book Request Status",

    /*Fixed Deposite*/
    fixed_deposit: "Fixed Deposit",
    account_title: "Account Title",
    depositTypeArr: [
        {key: "0", label: "Fixed Deposit-General", value: 0},
        {key: "1", label: "Double Money FD Account", value: 1},
        {key: "2", label: "Monthly Interest Paying FD", value: 2}
    ], TenureTypeArr: [
        {key: "0", label: "Month(s)", value: 0},
        {key: "1", label: "Pays", value: 1},
    ],
    select_tenure_type: "Select Tenure Type",
    tenure: "Tenure(Period)",
    select_tenure_period: "Select Tenure(Period)",
    auto_renewal: "Auto Renewal",
    auto_renewal_Type: [{label: "Yes", value: 0}, {label: "No", value: 1}],
    renewTitle: "Renew",
    renew: [{label: "Principle Only", value: 0}, {label: "Both Principle & interest", value: 1}],
    interestRate: "Interest Rate",
    deposit_advice_branch: "Deposit Advice Collection Branch",
    select_branch: "Select Branch",
    maturity_Date: "Maturity Date",
    Confirm: "Confirm",
    credit_interest_to: "Credit Interest To",
    selectTenureType: "Select Tenure Type",
    selectTenurePeriod: "Select Tenure",
    error_amount: "Amount is Required",
    branch: "branch",
    installment_start_date: "Installment Start Date",
    select_installment: "Select Installment Start Date",
    month: "Month",
    select_month: "Select Month",
    amount_per_installment: "Amount Per Installment",
    errorSelect_installment: "Select Installment Start Date",
    errorSelect_month: "Select Month",

    /*pay order screen*/
    delivery_location: "Delivery Location",
    select_delivery_location: "Select Delivery Location",
    deliveryTypeArr: [{key: 0, label: "Branch", value: 0}],
    beneficiary_name: "Beneficiary Name",
    pay_order_type: "Pay Order Collection Branch",

    /*BeneficiaryOtherCard screen*/
    beneficiary_other_card_title: "Other Credit Card -Add Beneficiary",
    beneficiary_bank_card_title: "City Bank Credit Card -Add Beneficiary",
    selectDeliveryLocation: "Select Delivery Locations",
    error_beneficiaryName: "Please enter your valid beneficiary name",

    /*Positive Pay Screen design*/
    cheque_date: "Cheque Date",
    select_cheque_date: "Select Cheque Date",
    cheque_book_number: "Check Book Number",
    unused_checkLeaf_number: "Unused Cheque Leaf Number",
    select_chequebook_number: "Select Cheque Book Number",
    select_unused_cheque_number: "Select Unused Cheque Leaf Number",

    /* Request Monitor*/
    request_type: "Request Type",
    request_status: "Request Status",
    select_request_type: "Select Request Type",
    select_request_status: "Select Request Status",
    requestTypeArray: [
        {key: "0", label: "Monthly DPS", value: 0},
        {key: "1", label: "Fixed Deposit", value: 1},
    ],
    requestStatusArray: [
        {key: "0", label: "All", value: 0},
        {key: "1", label: "Pending", value: 1},
        {key: "2", label: "Open", value: 2},
    ],
    account_title: "Account Title",
    account_number: "Account Number",
    start_date: "Start Date",

    /*Otp Lock Unlock*/
    reset_request: "Reset Request",
    select_otp_status: "Select Otp Status",
    resetRequestTypeArray: [
        {key: "0", label: "Active", value: 0},
    ],
    select_debit_credit: "Select Debit/Credit Card",
    current_otp_status: "Current Otp Status",
    lock: "Lock",
    unlock: "Unlock",
    error_otp_status: "Select Otp Status",
    error_debit_credit: "Card Number is Required",

    /*view_delete_beneficiary*/
    transfer_wcb: "Transfer Within City Bank",
    transfer_ob: "Transfer Other Bank",
    view_delete_beneficiary: "View Delete beneficiary",
    accountTxt: "Account",
    cardText: "Card",
    selectActNo: "Please Select Account Number",
    deleteAlert: "Are you sure you want to delete added beneficiary?",
    noBeneficiaryAdded: "No Beneficiary Added",
    delete: "Delete",
    biometricTitle: "Scan your Fingerprint on the mobile scanner to continue",
    biometricError: "Please validate using finger to login",

    /*error message*/
    error_debit_card: "Please select Debit Card",
    onlybKashTxt: "Only bkash customer account can be added",

    selMfs: "Select MFS",
    mfsTxt: "MFS",
    mfsList: [{label: "bKash Account", value: 0}],


    update_beneficiary_alert: "Please update this beneficiary information",
    settings: "Settings",

    error_account_same: "From and To account should not be same",
    error_select_to_type: "Please Select To Account",
    error_select_nickname_type: "select nick name",
    fund_transfer_own_account: "Fund Transfer Own Account",
    fund_transfer_city_account: "Fund Transfer City Account",
    transfer: "Transfer",
    fund_transfer_bank: "Fund Transfer Other Bank Account",

    error_grand_total_amount: "Grand total amount should be less than or equal to  available balance.",
    enter_amount: "Enter amount here",
    error_mobile_number: "Mobile number should be 11 digit and start with 01",
    payment_details: "Payment Details",

    /* Payments Details*/
    merchant_name: "Merchant Name",
    merchant_city: "Merchant City",
    payment_amount: "Payment Amount(BDT)",
    grandTotal_bdt: "Grand Total (BDT)",
    bill_number: "Bill Number",
    store_label: "Store Label",
    terminal_label: "Terminal Label",
    payment_details_note1: "1. Enter Amount or the total bill value of the goods purchased.",
    somethingWrong: "Something wrong please try after sometime",

    insufficientBal: "Insufficient balance to transfer money",
    success_transfer: "Successfully transferred",
    transferCity_props: [
        {label: "Single Fund Transfer", value: 0},
        {label: "Transfer from Beneficiary", value: 1}
    ],

    payment_card: "Select Card *",
    error_card_pin:"Card pin is Required",
    receipt:"Receipt",
    thank_you:"Thank You!",
    transaction_success: "Transaction Successfully",
    approval_id: "Approval ID 108417268210",
    customer_name: "Customer Name",
    source_account:"Source Account",
    receipt_amount:"Amount (BDT)",
    type:"Type",
    transaction_date:"Transaction Date & Time",
    another_qr_payment:"Another Qr Payment",
    save_share:"Save/Share",

    /*Qr Merchant Payment*/
        type_selection:"Type of Selection",
        select_card_qr:"Select the card(s) to perform QR Merchant Payment",
    transLogin:"Transaction with login only",
    transLimit:"Set up to 99 transaction limits without login",
    qr_notes:"If option 2 is selected, upon each successfully transaction the total limit will reduce by one",
    errorTransactionLimit: "Setup to 99 transaction limit without login",
    status:"Status",
    waiting:"Waiting",
    reference_number:"Reference Number",
    valid_till:"valid Till",
    resend_notification:"Re-send Notification",
    cancel_transfer:"Cancel Transfer",
    email_transfer_details:"Email Transfer Details",
    reclaim_money_to:"Reclaim Money To",
    select_reclaim_money:"Select Reclaim Money",
    error_reclaim_money:"Select Reclaim Money",
    from_account_card: "From Account/Card",
    enter_otp: "Enter Otp",
    transfer_type: "Transfer Type",
    single_transfer: "Single Transfer",
    transfer_from_beneficiary:"Transfer From Beneficiary",
    verifyOtp:"Verify OTP",

    ActNo:"A/c No.",
    mobileTxt:"Mobile",
    routingNo:"Routing No.",
    bankCode:"Bank Code",

    Transaction_success: "Transaction Successfully",
    trans_success_message:"Your fund has been transferred successfully, please check below details for reference.",
    addToFavorite: "Add To Favourite",



}