const CHANGE_LANG = "CHANGE_LANG";
const CHANGE_LOGIN_PREF = "CHANGE_LOGIN_PREF";
const SET_USER_DETAILS = "SET_USER_DETAILS";
const SET_SIGNUP_DETAILS = "SET_SIGNUP_DETAILS";
const ADD_BENEFICIARY = "ADD_BENEFICIARY";
const RESET_BENEFICIARY = "RESET_BENEFICIARY";
const CANCEL_EMAIL_TRANSFER_REQUEST = "CANCEL_EMAIL_TRANSFER_REQUEST";

export const accountActions = {
 CHANGE_LANG,
 CHANGE_LOGIN_PREF,
 SET_USER_DETAILS,
 SET_SIGNUP_DETAILS,
 ADD_BENEFICIARY,
 RESET_BENEFICIARY,
 CANCEL_EMAIL_TRANSFER_REQUEST
};
