const CHANGE_LANG = "CHANGE_LANG";
const CHANGE_LOGIN_PREF = "CHANGE_LOGIN_PREF";
const SET_USER_DETAILS = "SET_USER_DETAILS";
const SET_SIGNUP_DETAILS = "SET_SIGNUP_DETAILS";

export const accountActions = {
 CHANGE_LANG,
 CHANGE_LOGIN_PREF,
 SET_USER_DETAILS,
 SET_SIGNUP_DETAILS
};
